name: check updates
on:
  workflow_dispatch:
  schedule:
    - cron: "26 3 * * 1" # every monday at 3:26AM
jobs:
  check_updates:
    name: check updates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: install xmlstarlet
        run: sudo apt-get install -qqy xmlstarlet
      - name: compare current versions checksums
        run: ./.github/check-update.jdbc.sh || echo "::set-output name=JDBC_UPDATE_AVAILABLE::true"

  open_pr:
    name: open pull request
    needs:
      - check_updates
    if: needs.check_updates.outputs.JDBC_UPDATE_AVAILABLE == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: install nix
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-20.03

      - env:
          GPG_PASSPHRASE_JDK6: ${{ secrets.GPG_PASSPHRASE_JDK6 }}
        run: ./.github/fetch-jdk6.sh

      - name: update sources
        run: nix-shell --run "./.github/update-sources.jdbc.sh"

      - name: validate build
        run: nix-shell --pure --run "mvn -B package"

      - name: commit and open pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: nix-shell --run "./.github/open-pr.sh 'JDBC drivers' 'libsrc/JDBCDriverType4'"
