name: publish virtuoso jdbc
on:
  push:
    tags:
      - virtuoso-jdbc-*
jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-20.03
      - env:
          GPG_PASSPHRASE_JDK6: ${{ secrets.GPG_PASSPHRASE_JDK6 }}
        run: ./.github/fetch-jdk6.sh
      - env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          nix-shell --pure --keep BINTRAY_USERNAME --keep BINTRAY_TOKEN \
              --run "mvn -B deploy -pl virtuoso-jdbc-4.0,virtuoso-jdbc-4.1,virtuoso-jdbc-4.2,virtuoso-jdbc-4.3"
