name: publish virtuoso jdbc
on:
  push:
    tags:
      - virtuoso-jdbc-*
jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - env:
          GPG_PASSPHRASE_JDK6: ${{ secrets.GPG_PASSPHRASE_JDK6 }}
        run: ./.github/fetch-jdk6.sh
      - env:
          GITHUB_USER: ${{ env.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          nix-shell --pure --keep GITHUB_USER --keep GITHUB_TOKEN \
              --run "mvn -B deploy -pl virtuoso-jdbc-4.0,virtuoso-jdbc-4.1,virtuoso-jdbc-4.2,virtuoso-jdbc-4.3"
