name: verify branch
on:
  push:
    branches:
      - '**'
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-20.03
      - env:
          GPG_PASSPHRASE_JDK6: ${{ secrets.GPG_PASSPHRASE_JDK6 }}
        run: ./.github/fetch-jdk6.sh
      - run: nix-shell --pure --run "mvn -B package"
